활동 API 수정 완료
KGU-C-Lab/clab-platforms-server pull request #448
Opened 2024-08-06 09:18 UTC by mingmingmon

## Summary

> #447 

프론트 @Jeong-Ag님과 함께 회의한 결과 활동 API 수정 작업입니다.

## Tasks

- 활동 그룹 게시판 생성 API 수정 (스웨거 설명정보와 FEEDBACK 카테고리 중심으로)
- 활동 그룹 게시판 응답에 작성자 정보 추가

## ETC

## Screenshot

활동 그룹 게시판 생성 API 스웨거 설명 수정
![image](https://github.com/user-attachments/assets/8e50fedf-a553-4858-a4cd-75fa3f5aa53d)

카테고리가 FEEDBACK일 경우 내용을 필수로 등록해야 함
![image](https://github.com/user-attachments/assets/dd906597-5be8-4c43-ba06-49dcaf4b3281)

다른 카테고리의 경우 제목과 내용이 필수가 아님
<img width="387" alt="image" src="https://github.com/user-attachments/assets/f63ab212-dacb-4468-9b51-5864ec89f7e4">

활동 그룹 게시판 응답에 작성자 정보(아이디, 이름) 추가
![image](https://github.com/user-attachments/assets/d6c1c1f4-3397-4164-95b8-8f6dc15516eb)

2024-08-06 12:51 UTC, limehee requested changes

2024-08-06 12:51 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        validateRequestBody(requestDto);
`validateDueDateForAssignment`처럼 메소드의 기능을 명확하게 나타낼 수 있도록 해주세요. `validateRequestBody`라는 메소드명은 `requestDto`의 모든 세부 사항에 대해 유효성 검사를 하는 것처럼 보일 수 있습니다.

2024-08-06 12:51 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        return new PagedResponseDto<>(boards.map(board -> ActivityGroupBoardResponseDto.toActivityGroupBoardResponseDtoWithMemberInfo(board, externalRetrieveMemberUseCase)));
수정된 많은 부분에서 DTO에 인바운드 포트 인터페이스(UseCase)를 전달하고, DTO에서 이를 이용하도록 하고 있습니다. 그러나 DTO는 계층 간 데이터 전달을 위한 객체로, 그 외의 기능을 가져서는 안 됩니다. 역할과 책임의 분리를 위해 Application Layer에서 필요한 값을 DTO에 전달하는 방법으로 변경해 주시기 바랍니다.

2024-08-06 12:51 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupBoardResponseDto.java
> +        MemberDetailedInfoDto memberInfo = externalRetrieveMemberUseCase.getMemberDetailedInfoById(activityGroupBoard.getMemberId());
`memberId`, `memberName`만 필요한 경우라면 `getMemberBasicInfoById()` 메소드를 통해 `MemberBasicInfoDto`를 가져와 사용하는걸 권장합니다.

다른 DTO도 마찬가지입니다.

2024-08-07 07:16 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        return new PagedResponseDto<>(boards.map(board -> ActivityGroupBoardResponseDto.toActivityGroupBoardResponseDtoWithMemberInfo(board, externalRetrieveMemberUseCase)));
수정 사항 확인했습니다. 반영해주셔서 감사합니다.

2024-08-07 07:16 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupBoardResponseDto.java
> +        MemberDetailedInfoDto memberInfo = externalRetrieveMemberUseCase.getMemberDetailedInfoById(activityGroupBoard.getMemberId());
수정 사항 확인했습니다. 반영 감사합니다.

2024-08-07 07:32 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +                            .map(board -> FeedbackResponseDto.toFeedbackResponseDtoWithMemberInfo(board, externalRetrieveMemberUseCase))
`currentMember`를 조회한 것은, 내가 제출한 board를 가져오기 위함입니다.

map 안에 있는 `externalRetrieveMemberUseCase`는 현재 `MemberBasicInfoDto `객체를 전달하는 것으로 수정하였으며, 해당 정보는 feedBack 게시판에 대한 작성자 정보입니다. 

따라서 `currentMember`의 정보로는 `AssignmentSubmissionWithFeedbackResponseDto`의 `memberId`, `memberName `필드를 채우기 위함이고, map 안의 `memberBasicInfoDto`는 `FeedbackResponseDto`의 `memberId`, `memberName `필드를 채우기 위함입니다.

즉 코드 중복이 아닌 다른 정보를 추출하기 위한 작업입니다.

2024-08-07 10:36 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +                            .map(board -> FeedbackResponseDto.toFeedbackResponseDtoWithMemberInfo(board, externalRetrieveMemberUseCase))
이해했습니다! 감사합니다.

2024-08-11 05:58 UTC, limehee commented
해당 작업과 무관한 `FileController`, `FileService`가 커밋에 추가되었습니다.
확인 부탁드립니다.

2024-08-11 06:02 UTC, limehee approved these changes

2024-08-11 07:46 UTC, SongJaeHoonn approved these changes

2024-08-11 11:20 UTC, merged