활동 상세 조회 API 응답 수정 완료
KGU-C-Lab/clab-platforms-server pull request #459
Opened 2024-08-12 07:13 UTC by mingmingmon

## Summary

> #455 

활동 상세 조회 API의 응답을 ActivityGroupDetailResponseDto로 통일하였습니다. 해당 responseDto에는 ActivityGroup 도메인 엔티티의 모든 내용이 포함되어 있습니다.

## Tasks

-  활동 상세 조회 API의 응답 ActivityGroupDetailResponseDto로 통일하기

## Screenshot

<img width="515" alt="image" src="https://github.com/user-attachments/assets/e2f0cc50-6723-4275-8447-409d38e3ee3b">

2024-08-12 07:15 UTC, limehee commented
해당 응답을 전달받는 모든 화면에서 `ActivityGroupDetailResponseDto`의 정보 모두를 필요로 하는 걸까요?
정보 모두를 필요로 하는 게 아니라면, DTO를 추가로 작성하여 필요한 만큼의 정보만 반환하는 게 좋다고 판단됩니다.

2024-08-12 07:25 UTC, mingmingmon commented
> 해당 응답을 전달받는 모든 화면에서 `ActivityGroupDetailResponseDto`의 정보 모두를 필요로 하는 걸까요? 정보 모두를 필요로 하는 게 아니라면, DTO를 추가로 작성하여 필요한 만큼의 정보만 반환하는 게 좋다고 판단됩니다.

해당 작업을 진행하게 된 이유에 대해서 이슈에 적어놓았는데 정작 PR에는 설명이 부족했던 것 같네요.

프론트 @Jeong-Ag님의 요청으로 활동 상세조회 API에서 카테고리가 STUDY, PROJECT에 상관 없이 모든 정보가 반환될 수 있도록 수정하는 작업을 시작하게 되었습니다.

현재 프론트에서 활동을 생성할 경우 **STUDY, PROJECT 구분 없이 `imageUrl, curriculum, startDate, endDate, techStack, githubUrl`을 선택입력으로 처리**하고 있다고 합니다. 

**이전의 상세조회 API**에서는 STUDY의 경우는 `ActivityGroupStudyResponseDto`에 imageUrl과 curriculum이 담기고, PROJECT에서는 `ActivityGroupProjectResponseDto`에 `imageUrl, startDate, endDate, techStack, githubUrl`이 담겨 반환되고 있음을 설명드렸습니다만,

**`ActivityGroupDetailResponseDto`로 통일하여 카테고리에 상관없이 모두 반환되도록 수정하시길 원해서** 해당 작업이 진행되었습니다. 

백엔드의 이전 API 설계에 따르면 `ActivityGroupStudyResponseDto`와 `ActivityGroupProjectResponseDto`를 따로 두고 있었습니다. 이로 미루어보아 프론트 측에서 활동 그룹을 생성할 때 카테고리를 구분해서 `curriculum, startDate, endDate, techStack, githubUrl`을 분리해서 받을 수 있도록 구현하는 것을 기대한 것 같습니다.

그러나 프론트측에서 활동 생성 화면에서 카테고리 구분 없이 해당 칼럼들을 선택 입력 처리를 하고 있다고 하였고, 상세조회 페이지에서는 관련 칼럼이 모두 반환되었으면 좋겠다고 요청하였습니다.

2024-08-12 07:27 UTC, limehee requested changes

2024-08-12 07:27 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
> -            return ActivityGroupProjectResponseDto.create(details.getActivityGroup(), details.getGroupMembers(), activityGroupResponseDtos, groupMemberResponseDtos, isOwner);
반환 정보가 수정됨에 따라 `ActivityGroupStudyResponseDto`와 `ActivityGroupProjectResponseDto`는 프로젝트에서 사용되지 않는 코드가 되었습니다. 해당 클래스 제거 바랍니다.

2024-08-12 07:27 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
Line 64
```java
public Object getActivityGroup(Long activityGroupId) {
```
`getActivityGroup()` 메소드의 반환 정보가 변경됨에 따라, 이 메소드의 반환형을 `ActivityGroupDetailResponseDto`로 변경해야 합니다. 이에 따라, `getActivityGroup()` 메소드를 호출하는 Controller 메소드도 함께 수정해야 합니다.

2024-08-12 07:37 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
> -            return ActivityGroupProjectResponseDto.create(details.getActivityGroup(), details.getGroupMembers(), activityGroupResponseDtos, groupMemberResponseDtos, isOwner);
삭제완료했습니다!

2024-08-12 07:38 UTC, mingmingmon commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
명확한 리턴타입 명시하도록 수정했습니다

2024-08-12 07:49 UTC, limehee approved these changes

2024-08-14 05:11 UTC, SongJaeHoonn approved these changes

2024-08-14 06:08 UTC, merged