도서 대출시 도서의 대출자 정보가 승인자로 저장되는 버그 수정 완료
KGU-C-Lab/clab-platforms-server pull request #483
Opened 2024-08-19 07:48 UTC by SongJaeHoonn

## Summary

> #482 

도서 대출시, 책의 대출자 정보(`borrowerId`, `borrowName`)가 도서를 승인해주는 관리자의 정보로 저장되는 버그를 수정했습니다.

## Tasks

- 도서 승인시, 대출자 정보가 승인자 정보로 저장되는 로직 수정

## ETC

## Screenshot

- 도서 목록 조회
![스크린샷 2024-08-19 154432](https://github.com/user-attachments/assets/daf4ebdd-4dc9-47e2-a613-347be302b6be)

- 도서 상세 조회
![스크린샷 2024-08-19 155125](https://github.com/user-attachments/assets/cce6a792-9e86-405d-a9fd-58072636ebbf)

2024-08-19 08:21 UTC, limehee requested changes

2024-08-19 08:21 UTC, limehee commented on src/main/java/page/clab/api/domain/library/book/application/service/BooksByConditionsRetrievalService.java
> +        String borrowerId = externalRetrieveBookLoanRecordUseCase.getBorrowerIdForBook(book.getId());
```java
public Long approveBookLoan(Long bookLoanRecordId) {
    BookLoanRecord bookLoanRecord = retrieveBookLoanRecordPort.findByIdOrThrow(bookLoanRecordId);
    String borrowerId = bookLoanRecord.getBorrowerId();
    ...
    book.borrowBook(borrowerId);
    ...
}
```
```java
public void borrowBook(String borrowerId) {
    validateBookIsNotBorrowed();
    this.borrowerId = borrowerId;
}

public void returnBook(String borrowerId) {
    validateCurrentBorrower(borrowerId);
    this.borrowerId = null;
}
```
`book.borrowBook()` 메소드의 구현을 보면, 도서 대출 승인 시 `Book` 객체에 `borrowerId`를 지정하고, 도서 반납 시에 `borrowerId`를 `null`로 설정하고 있어요. 이와 같은 이유로, `borrowerId`를 DB에서 조회하는 건 불필요해 보여요. 또한, `getBorrowerIdForBook()` 메소드의 구현을 보니, 해당 도서 ID에 대한 대출 기록이 여러 개일 경우 반환 값이 `List<>`로 올 수 있고, 대출 기록이 없을 경우 `orThrow`로 인해 정상적인 조회가 이루어지지 않을 가능성도 있어 보여요.

해당 부분 검토해서 수정 부탁드릴게요.

2024-08-19 08:40 UTC, mingmingmon approved these changes
고생하셨습니다!

2024-08-19 16:55 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/library/book/application/service/BooksByConditionsRetrievalService.java
> +        String borrowerId = externalRetrieveBookLoanRecordUseCase.getBorrowerIdForBook(book.getId());
`borrowerId`를 가져오는 과정을 따로 DB에서 조회하지 않고,  직접 `Book` 객체에서 가져올 수 있는 아주 간단한 방법이 있었군요! 
이렇게 되면 `externalRetrieveBookLoanRecordUseCase`에서 `borrowerId`를 가져오는 로직을 작성하지 않아도 되어 더욱 코드가 간결해질 것 같아요. 
`null`을 체크해야 하는 과정을 `retrieveBookDetails()`와 `retrieveBooks()`에서 진행해야 하긴 하지만, 삼항 연산자로 쉽게 관리할 수 있을 것 같습니다.

해당 부분 검토 후 수정 완료했고, 다음은 테스트 결과입니다.
- **책 두 권이 아무에게도 대출되지 않은 상태**에서 도서 목록 조회
![스크린샷 2024-08-20 010827](https://github.com/user-attachments/assets/2a4dfbcf-1b6e-4d20-9b16-b2b1d85ef830)

- 1번 책을 대출 **요청**한 상태
![스크린샷 2024-08-20 010923](https://github.com/user-attachments/assets/5dcdb476-bd93-4e5a-ba1f-caa0140ffcb5)

-  1번 책 대출을 **승인**한 상태
![스크린샷 2024-08-20 011053](https://github.com/user-attachments/assets/811a03f4-0553-4c3f-8d90-d5a91e7dedd4)

- 1번 책 대출이 **승인된 상태에서 도서 목록 조회**
![스크린샷 2024-08-20 011252](https://github.com/user-attachments/assets/b935b4a5-3bde-4d3f-bca7-174f6bcc2525)

- 1번 책 대출이 **승인된 상태에서 도서 상세 조회**
![스크린샷 2024-08-20 015354](https://github.com/user-attachments/assets/ed08c692-4849-4d5f-8346-8ed2a242978d)

- 1번 책이 **반납된 후 도서 목록 조회**
![스크린샷 2024-08-20 011401](https://github.com/user-attachments/assets/0c2a6c18-b661-45d8-a45c-757f28102472)

- 1번 책이 **반납된 후 도서 상세 조회**
![스크린샷 2024-08-20 013548](https://github.com/user-attachments/assets/d6ff0619-65de-402c-a64a-736b9a99cacf)

2024-08-19 16:56 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/library/book/application/service/BookDetailsRetrievalService.java
> +        MemberBasicInfoDto memberBasicInfo = externalRetrieveMemberUseCase.getMemberBasicInfoById(borrowerId);
로직 변경 후, 해당 변수명은 사용하지 않게 되었습니다.

2024-08-19 16:56 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/library/book/application/service/BooksByConditionsRetrievalService.java
> +        MemberBasicInfoDto memberBasicInfo = externalRetrieveMemberUseCase.getMemberBasicInfoById(borrowerId);
로직 변경 후, 해당 변수명은 사용하지 않게 되었습니다.

2024-08-19 22:01 UTC, limehee commented on src/main/java/page/clab/api/domain/library/book/application/service/BookDetailsRetrievalService.java
>      }
```java
@Transactional(readOnly = true)
@Override
public BookDetailsResponseDto retrieveBookDetails(Long bookId) {
    Book book = retrieveBookPort.findByIdOrThrow(bookId);
    String borrowerName = getBorrowerName(book);
    return mapToBookDetailsResponseDto(book, borrowerName);
}

private String getBorrowerName(Book book) {
    String borrowerId = book.getBorrowerId();
    if (borrowerId != null) {
        return externalRetrieveMemberUseCase.getMemberBasicInfoById(borrowerId).getMemberName();
    }
    return null;
}
```

이와 같이 조건부 로직을 별도의 메서드로 분리하면 가독성에 더 좋을 것 같아요.

2024-08-19 22:03 UTC, limehee commented on src/main/java/page/clab/api/domain/library/book/application/service/BooksByConditionsRetrievalService.java
> +        String borrowerId = externalRetrieveBookLoanRecordUseCase.getBorrowerIdForBook(book.getId());
많이 고민한 흔적이 보이네요. 고생 많으셨어요.

2024-08-20 00:25 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/library/book/application/service/BookDetailsRetrievalService.java
>      }
피드백 다시한번 감사합니다! 가독성 있게 수정 완료했습니다.

2024-08-20 00:27 UTC, limehee approved these changes

2024-08-20 00:28 UTC, merged