합격자 계정 생성 로직 리팩토링 완료
KGU-C-Lab/clab-platforms-server pull request #494
Opened 2024-08-22 09:06 UTC by SongJaeHoonn

## Summary

> #489 

합격자에 대한 계정 생성 로직을 가독성 있도록 메서드를 분리하고, 이미 `Position`이 정해져 있는 회원에 대한 로그도 추가했습니다.

## Tasks

- `validateApplicationIsPass` 메서드 분리
- 이미 등록된 회원임을 알려주는 로그 추가

## ETC

합격자 계정 생성 flow에서 빠진 유효성 검사가 있는지 확인해봤으나, 이메일 전송 관련해서도 이미 이메일 도메인 안에서 처리되고 있고, 이미 등록된 회원을 골라내는 것이나 미승인 지원서를 판별하는 행위도 이미 로직에 녹아있으므로, 
이미 충분하다고 생각해 예외를 더 추가하지는 않았습니다.

## Screenshot

- 지원한 두 명중 둘 다 합격한 상태
```
{
  "success": true,
  "data": {
    "currentPage": 0,
    "hasPrevious": false,
    "hasNext": false,
    "totalPages": 1,
    "totalItems": 2,
    "take": 2,
    "items": [
      {
        "studentId": "201912000",
        "recruitmentId": 1,
        "name": "김철수",
        "contact": "01012345678",
        "email": "thdwogns121@naver.com",
        "department": "AI컴퓨터공학부",
        "grade": 4,
        "birth": "2004-01-01",
        "address": "경기도 수원시 영통구 광교산로 154-42",
        "interests": "백엔드",
        "otherActivities": "경기대학교 컴퓨터공학과 학생회",
        "githubUrl": "https://github.com/KGU-C-Lab",
        "applicationType": "NORMAL",
        "isPass": true,
        "updatedAt": "2024-08-22T15:55:45.819818",
        "createdAt": "2024-08-22T14:35:07.643876"
      },
      {
        "studentId": "202022222",
        "recruitmentId": 1,
        "name": "송재훈",
        "contact": "01011111111",
        "email": "thdwogns011207@gmail.com",
        "department": "AI컴퓨터공학부",
        "grade": 3,
        "birth": "2001-12-07",
        "address": "경기도 수원시 영통구 광교산로 154-42",
        "interests": "프론트엔드",
        "otherActivities": "경기대학교 컴퓨터공학과 학생회",
        "githubUrl": "https://github.com/KGU-C-Lab",
        "applicationType": "NORMAL",
        "isPass": true,
        "updatedAt": "2024-08-22T15:57:05.042394",
        "createdAt": "2024-08-22T13:54:01.392821"
      }
    ]
  }
}
```

- 통합 합격자 생성
```
{
  "success": true,
  "data": [
    "201912000",
    "202022222"
  ]
}
```

- 이미 등록된 회원일 시 (로그만 올라오고 정상 진행)
![스크린샷 2024-08-22 160337](https://github.com/user-attachments/assets/1ba0cf55-c657-4fb7-9ebc-bfcd60c5c2a4)

- 이메일 전송 결과
![스크린샷 2024-08-22 160652](https://github.com/user-attachments/assets/e3dc469a-efa1-4730-a61e-c87d65381bce)

![스크린샷 2024-08-22 160723](https://github.com/user-attachments/assets/e0960851-24fd-421f-a99a-6600b1355b92)

- 202022222만 이미 Position이 정해진 Member이고, 201912000은 지원해서 합격된 상태에서 합격자 통합 생성
![스크린샷 2024-08-22 174628](https://github.com/user-attachments/assets/f506d704-57ba-4690-b900-2e4fb9b9acf3)

그리고 이후 동작은 이전 결과와 같습니다. (같은 결과가 201912000에서만 나타납니다)
합격자 개별 생성도 이전 결과와 같습니다.

2024-08-23 01:09 UTC, limehee requested changes

2024-08-23 01:09 UTC, limehee commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +                    Member member = Application.toMember(application);
`Application` 도메인에서 `Member` 도메인을 직접 참조하여 객체를 생성하는 설계 방식은 두 도메인 간의 강한 결합을 초래할 수 있어요. 이로 인해 각 도메인의 책임이 명확하게 분리되지 않고, 변경 시에도 상호 영향을 미칠 수 있죠. 이러한 문제를 해결하기 위해, `Member` 도메인에서 필요한 객체를 직접 생성하는 대신, 도메인 이벤트(Domain Event)를 활용하는 것을 추천드려요.

도메인 이벤트를 발행함으로써 `Application` 도메인은 `Member` 도메인의 내부 구현에 대한 의존성을 줄일 수 있어요. 예를 들어, `Application` 도메인에서 특정 이벤트가 발생하면, 그에 대응하는 도메인 이벤트를 발행하고, `Member` 도메인에서는 해당 이벤트를 처리하여 객체를 생성하거나 상태를 변경하는 식으로 동작할 수 있어요.

이러한 방식은 Aggregate의 경계를 명확히 하여, 각 도메인이 자신의 책임 내에서만 동작하도록 하면서도 필요한 상호작용을 가능하게 해요. 결과적으로 시스템의 유연성과 확장성이 높아지고, 도메인 간의 결합도는 낮아지게 되죠.

따라서, `Application` 도메인이 `Member` 도메인에 직접 의존하지 않도록 도메인 이벤트를 사용하여 `Member` 도메인 내부에서 객체가 생성되도록 변경하는 접근이 적절해 보여요.

2024-08-23 07:57 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +                    Member member = Application.toMember(application);
`Application` 도메인에서 `toMember()`를 통해 Member를 직접 생성하고 반환하는 로직 때문에 두 도메인 간의 결합도가 증가해 의존성이 높아지게 되고, 확실한 책임 분리가 이뤄지지 않는다는 문제를 확인했습니다. 
따라서, `Domain Event`를 활용해 두 도메인이 각자의 책임만 가질 수 있도록 하는 것이 좋은 생각인 것 같습니다.

원래 'Member'에서 Event를 이미 사용하고 있는데, 어떻게 사용해야 할지 모르고 있었습니다. 
이번 기회에 Domain Event를 적용해보며 DDD(Domain-Driven Design)에 대해 알아볼 수 있는 좋은 기회가 될 것 같아요.

피드백 해주신 내용을 바탕으로, 도메인 이벤트를 사용해 `Member` 도메인에 대해 `Application` 도메인이 강결합되지 않도록 적용해보겠습니다!

2024-08-24 02:48 UTC, mingmingmon approved these changes
확인 완료했습니다! 고생하셨습니다

2024-08-27 07:23 UTC, limehee requested changes

2024-08-27 07:23 UTC, limehee commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +    private boolean isRegisteredMember(Member member) {
`isRegisteredMember()`라는 메소드명은 등록된 회원인지 여부를 확인하는 로직을 갖는 메소드처럼 보이게 만들어요. 메소드명 수정 부탁드려요.

2024-08-27 07:23 UTC, limehee commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
>          externalRegisterPositionUseCase.save(position);
`Position`도 `Member`와 동일한 Aggregate로 분류되기 때문에, `Position` 또한 이벤트를 리스닝(구독)하여 등록되도록 하는 것이 더 좋은 패턴일 것 같아요. 이렇게 하면 각 도메인 객체들이 적절한 시점에 서로 독립적으로 처리되면서도 일관성을 유지할 수 있을 거에요.

2024-08-27 07:23 UTC, limehee commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +                    eventPublisher.publishEvent(new MemberCreatedEvent(this, application));
현재 `MemberCreatedEvent`는 `Member` 도메인에서 새로운 멤버가 추가될 때 발행되는 이벤트로 사용되어야 해요. 하지만 코드에서 `Application` 도메인과 연관된 시점에 발행되고 있어요. 따라서 `ApplicationApprovedEvent`라는 새로운 이벤트를 설계하고, 이를 `Member` 도메인에서 리스닝하여 멤버가 생성되도록 수정하는 것이 더 적절해 보여요.

2024-08-27 17:23 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
>          externalRegisterPositionUseCase.save(position);
`Position`도 Position 도메인에서 `PositionCreatedEvent`를 만들어 구현해볼까 생각해봤으나, `Member`처럼 `Position` 도메인에서 새로운 Position이 추가될 때 발행되는 이벤트여야 한다고 생각해 `Application` 도메인 안에서 새로운 Event 클래스를 구현하는 방향으로 설계했습니다. 
생각하신 방향과 다르다면 피드백 해주시면 감사하겠습니다! 아직 도메인 이벤트에 대한 설계나 이해가 미숙해서 많은 어려움이 있네요.

2024-08-27 17:23 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +                    eventPublisher.publishEvent(new MemberCreatedEvent(this, application));
피드백 감사합니다! Member 생성시 적절한 도메인 이벤트 구현이 어려워 최대한 기존의 코드를 따라가는 방식으로만 설계했었는데, 새롭게 `ApplicationApprovedEvent`를 설계하는 방법을 제안해주셔서 정말 감사합니다.
`ApplicationApprovedEvent`를 생성 후, Member 도메인에서 리스너 클래스를 하나 더 만드는 방식으로 간단히 설계했습니다(Application을 통해 Member를 생성하는 행위는 한 군데에서만 진행되므로).

2024-08-28 12:52 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +        eventPublisher.publishEvent(new PositionCreatedByApplicationEvent(this, position));
해당 부분에서도 결합이 일어나고 있었군요. 피드백과 함께 좋은 아이디어 주셔서 정말 감사합니다!

Position 객체를 생성하는 데 말씀해주신 방법들을 고려하여 코드를 수정해보았습니다.
1. 우선 지원 합격 처리 후, 합격자를 생성할 때 Member 생성 이벤트 발행 -> Position 생성 이벤트 발행 순으로 흘러갑니다.
2. Member 생성 이벤트가 발행되면, `Member` 도메인에서 해당 이벤트를 리스닝하여 Member 객체를 생성합니다.
3. 해당 이벤트가 끝나고 새롭게 등록된 `Member` 객체를 조회하여 반환합니다.
4. `createMemberFromApplication()`에서는 반환된 `Member` 객체를 받아 `createPositionByMember()`에 파라미터로 넘겨집니다.
5. 파라미터로 넘어온 `Member` 객체의 id 값을 이용해 `Position`을 생성하는 이벤트를 발행하게 됩니다.

말씀해주신 `Member`가 정상적으로 등록되었는지 검사하여 필요시 롤백하는 것은, 이미 `createMemberByApplication()`에서 등록된 `Member`를 조회할 때 진행되게 됩니다.

여러 명의 지원서 등록 및 합격 처리 후 통합 계정 생성 테스트도 성공적으로 완료했습니다!

2024-08-28 12:52 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +                    Member member = Member.fromApplication(application);
해당 메서드에서 기존 멤버까지 반환을 해야 했기에 기존 `Member`이든, 새로 등록된 `Member`이든 반환할 Member 객체가 필요했습니다. 따라서 `save`만 도메인 이벤트로 처리하고, Member 객체를 임시로 생성하여 반환했었습니다.

하지만, 이것 또한 `Application` 도메인에서 `Member` 를 직접 참조하는 것임을 깨닫게 되었고, Member 생성 도메인 이벤트 처리 후, `externalRetrieveMemberUseCase`를 통해 등록된 Member를 조회해 반환하도록 수정했습니다.

2024-08-28 12:53 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/community/accuse/application/event/AccuseEventProcessor.java
> +}
수정 완료했습니다! 감사합니다.

2024-08-28 15:22 UTC, limehee commented on src/main/java/page/clab/api/domain/memberManagement/member/domain/Member.java
> +}
파일 끝 개행이 제거되었어요.

2024-08-28 15:22 UTC, limehee commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +        eventPublisher.publishEvent(new PositionCreatedByApplicationEvent(this, position));
지원자 중 일부가 이미 회원으로 등록된 경우에도 잘 동작하는지 확인 부탁드려도 될까요?

2024-08-28 15:30 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/memberManagement/member/domain/Member.java
> +}
확인 후 수정 완료했습니다!

2024-08-28 15:41 UTC, limehee commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +        eventPublisher.publishEvent(new PositionCreatedByApplicationEvent(this, position));
이미 회원으로 등록된 지원자의 신청을 승인하여 계정 생성에 실패하거나, 중복키 등의 이유로 멤버 생성에 실패하는 등의 경우도 대응이 되고있는지 궁금합니다.

2024-08-28 16:09 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
> +        eventPublisher.publishEvent(new PositionCreatedByApplicationEvent(this, position));
이미 회원으로 등록된 지원자라면 계정 생성을 추가로 진행하지 않고, `Position`도 추가로 생성되지 않습니다.
회원이 여러 개의 계정을 갖지 않으므로, 이미 회원으로 등록된 지원자의 계정을 생성할 필요가 없다고 생각했습니다.

또한 `Application`이 생성될 때 이미 `Member`엔티티에 필요한 validation이 검증되기 때문에 크게 신경쓰지 않았습니다.

중복 키에 관해서는 현재 중복 키로 인한 오류가 발생할 곳이 `Id`밖에 없는데, 이미 지원서를 통해 멤버 객체를 생성할 때 `Id`를 통해 이미 등록되어 있는 멤버인지 확인하는 로직을 거치게 되므로 중복 키 오류가 발생할 이유가 없다고 생각했습니다.

2024-08-29 00:18 UTC, limehee requested changes

2024-08-29 00:18 UTC, limehee commented on src/main/java/page/clab/api/domain/memberManagement/member/domain/Member.java
> +    public static Member fromApplication(Application application) {
이벤트를 발행할 때 `Application` 도메인 객체 원본을 직접 전달하지 않고, 별도의 DTO를 설계하여 전달하는 것이 더 바람직할 것 같아요. 예를 들어, '모집' 도메인과 '회원' 도메인을 각각의 모듈로 분리한다고 가정했을 때, 현재의 방식으로 진행하면 두 모듈이 독립적으로 실행될 수 없고, 상호 연결이 필요하게 돼요. 이는 결국 새로운 결합을 초래할 수 있습니다.

2024-08-29 05:12 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/memberManagement/member/domain/Member.java
> +    public static Member fromApplication(Application application) {
`Application` 객체 원본 대신 Dto를 설계하여 넘겨준다면 모듈 간 결합도를 줄이고 독립성을 유지할 수 있겠네요! 감사합니다. 
`ApplicationMemberCreationDto`를 새롭게 설계하여 `toMember`에 적용할 수 있도록 수정 완료했습니다 .
파라미터를 Dto로 변경하니, `fromApplication`이라는 메서드명이 어색해서 더욱 확실한 의미를 갖는 `toMember`로 이름을 변경했습니다.

2024-08-29 05:20 UTC, limehee commented on src/main/java/page/clab/api/domain/memberManagement/member/domain/Member.java
> +    public static Member fromApplication(Application application) {
고민의 흔적이 보이네요. 고생 많으셨어요.

2024-08-29 05:24 UTC, limehee approved these changes

2024-08-29 05:25 UTC, merged