feat: 업로드된 파일 권한별 접근 로직 구현
KGU-C-Lab/clab-platforms-server pull request #504
Opened 2024-08-23 18:32 UTC by mingmingmon

## Summary

> #502

업로드된 파일에 URL로 접근할 때 파일 카테고리마다 적절한 접근 기준에 따라 파일을 반환하도록 하였습니다. **파일경로에 접근할 때 JWT와 함께 요청**을 보내야 합니다.

- `"boards", "profiles", "activity-photos", "membership-fee"` 의 경우 GUEST 이상인 경우 접근가능
-  `"members"`의 경우 업로드 본인만 접근가능
-  `"assignments"`의 경우 제출자와 스터디장, ADMIN 이상인 경우 접근 가능

## Tasks

업로드된 파일 접근 권한 검사 후 제어

## ETC
- 해당 작업내용이 적용되면 파일 접근 시 JWT를 함께 담아서 요청해야 하는데, 프론트에서 파일 접근 로직에  코드 수정이 일어날 것 같습니다. 제가 구현한 방향이 맞는지 확인부탁드립니다.

## Screenshot

- 활동사진은 GUEST 로그인 이상의 경우 파일 반환
![image](https://github.com/user-attachments/assets/02a20cf5-cc25-4564-9753-b24503ff3bd1)

- 개인 클라우드 경로 파일은 본인만 확인가능 아래는 GUEST 로그인한 사용자로 접근한 경우
![image](https://github.com/user-attachments/assets/fe32fba7-ad82-4113-bbf0-d61d159dda42)

- 과제의 경우 제출자와 스터디장, ADMIN 사용자만 확인가능
![image](https://github.com/user-attachments/assets/96c1a893-5953-47e3-8013-da9901622566)
![image](https://github.com/user-attachments/assets/d351db56-b04c-49c7-93cd-f2f6080bb146)

2024-08-24 04:07 UTC, limehee requested changes

2024-08-24 04:07 UTC, limehee commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +            case "members":
현재의 구조는 카테고리별로 어떤 사용자가 접근할 수 있는지 명확하게 파악하기 어렵고, 확장성 측면에서도 다소 부족하다고 판단돼요.

이를 개선하기 위해, `Map<>`을 활용하여 권한별로 접근 가능한 카테고리를 명시하고, 이를 기반으로 접근 권한을 확인하는 방법을 제안드려요. 이와 같은 구조로 변경하면, 권한별로 묶인 카테고리를 한눈에 쉽게 파악할 수 있고, 향후 변경 사항이 생겼을 때에도 카테고리를 쉽게 추가하거나 삭제할 수 있어 유지보수에 용이할 거에요.

아래는 `Map<>`을 이용해서 권한별 접근 가능한 카테고리를 명시하는 예시 코드에요.

```java
private static final Map<Role, Set<String>> roleCategoryMap = Map.of(
        Role.GUEST, Set.of("boards", "profiles", "activity-photos", "membership-fee"),
        Role.USER, Set.of("boards", "profiles", "activity-photos", "membership-fee", "assignments"),
        Role.ADMIN, Set.of("boards", "profiles", "activity-photos", "membership-fee", "members", "assignments"),
        Role.SUPER, Set.of("boards", "profiles", "activity-photos", "membership-fee", "members", "assignments")
);
```

제가 작성한 예시 코드에서 권한 계층을 반영해서 카테고리를 중복 명시하지 않아도 되게 리팩토링하셔도 되고, 위 구조로 기본적인 권한 검사를 진행하고, 추가 검사 로직을 붙이셔도 돼요.

2024-08-24 04:07 UTC, limehee commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        GrantedAuthority authority = authentication.getAuthorities().iterator().next();
인증되지 않은 사용자의 요청인 경우(authentication이 null인 경우) `getAuthorities()`에서 `NullPointerException`이 발생해요. 예외 처리 추가 부탁드려요.

2024-08-24 04:09 UTC, limehee requested changes

2024-08-24 04:09 UTC, limehee commented on src/main/java/page/clab/api/global/config/WebConfig.java
> +import java.io.File;
불필요한 import 문이 추가되었어요. 제거 부탁드려요.

2024-08-24 13:25 UTC, mingmingmon commented on src/main/java/page/clab/api/global/auth/filter/FileAccessControlFilter.java
> +        if (requestURI.startsWith("/resources/files/")) {
수정 완료했습니다!

2024-08-24 13:26 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +            case "boards", "profiles", "activity-photos", "membership-fee":
앗 그렇군요.` activity-photos`는` authentication` 상관 없이 모두 접근할 수 있도록 수정했습니다.

2024-08-24 13:27 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        String basePath = "/resources/files/";
주의사항 설명 감사합니다! `/ `생략하고 진행하니 오류가 나더라구요

2024-08-24 13:27 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        if (category == null)
`  if (category == null || category.isEmpty())
            return false;` 로 수정해습니다!

2024-08-24 13:29 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +            case "members":
피드백 감사합니다. 훨씬 더 가독성이 좋아졌습니다.

2024-08-24 13:31 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        GrantedAuthority authority = authentication.getAuthorities().iterator().next();
```
if (authentication == null || authentication.getAuthorities() == null || authentication.getAuthorities().isEmpty())
            return false;
```
위와 같이 처리했습니다. `false`를 반환하는 경우 `FileAccessControlFilter`는 `ResponseUtil.sendErrorResponse(response, HttpServletResponse.SC_UNAUTHORIZED);`를 응답으로 반환하도록 하고 있습니다.

2024-08-24 13:55 UTC, limehee commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        GrantedAuthority authority = authentication.getAuthorities().iterator().next();
인증되지 않은 사용자를 판별하는 로직을 `AuthUtil`로 옮기면 책임 분리가 더 확실해질 것 같아요. 피드백 반영 감사합니다.

2024-08-24 14:20 UTC, limehee commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        switch (category) {
case마다 하드코딩해서 관리하기 보다는 아래와 같이 관리하는 방식은 어떤지 건의드립니다.

`roleCategoryMap` 작업해주신 것처럼 권한과 카테고리의 관계를 Map을 통해 관리하고, 각 카테고리마다 별도의 검증 로직을 메서드로 분리하면, 새로운 카테고리가 추가될 때 쉽게 확장할 수 있을 것으로 보여요.

```java
private static final Map<String, BiFunction<String, Authentication, Boolean>> categoryAccessMap = Map.of(
    "boards", (url, auth) -> true,
    "profiles", (url, auth) -> true,
    "membership-fee", (url, auth) -> true,
    "activity-photos", (url, auth) -> true,
    "members", this::isMemberAccessible,
    "assignments", this::isAssignmentAccessible
);

public boolean isUserAccessibleByCategory(String category, String url, Authentication authentication) {
    if (authentication == null || authentication.getAuthorities() == null || authentication.getAuthorities().isEmpty()) {
        return false;
    }

    GrantedAuthority authority = authentication.getAuthorities().iterator().next();
    String roleName = authority.getAuthority().replace("ROLE_", "");
    Role role = Role.valueOf(roleName);

    if (!roleCategoryMap.getOrDefault(role, Set.of()).contains(category)) {
        return false;
    }

    return categoryAccessMap.getOrDefault(category, (u, a) -> false).apply(url, authentication);
}

private boolean isMemberAccessible(String url, Authentication authentication) {
    UploadedFile uploadedFile = uploadedFileService.getUploadedFileByUrl(url);
    String uploaderId = uploadedFile.getUploader();
    return authentication.getName().equals(uploaderId);
}

private boolean isAssignmentAccessible(String url, Authentication authentication) {
    UploadedFile uploadedFile = uploadedFileService.getUploadedFileByUrl(url);
    String uploaderId = uploadedFile.getUploader();
    String[] parts = url.split("/");
    Long activityGroupId = Long.parseLong(parts[4]);

    return authentication.getName().equals(uploaderId) ||
           activityGroupAdminService.isMemberGroupLeaderRole(activityGroupId, authentication.getName());
}
```

2024-08-25 04:46 UTC, limehee commented on src/main/java/page/clab/api/global/auth/util/AuthUtil.java
> +    public static Boolean isUserUnAuthenticated (Authentication authentication) {
`(` 앞에 불필요한 공백이 추가되었어요. 확인 부탁드려요.

2024-08-25 04:46 UTC, limehee commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +    }*/
수정 이전의 코드를 주석으로 남겨놓은 이유가 있을까요?

2024-08-25 04:49 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +    }*/
동감입니다.

2024-08-25 05:10 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +    private boolean isMemberAccessible(String url, Authentication authentication) {
여기서는 `Member`라는 명칭이 사용되고, `isUserAccessibleAtFile`이나 `isUserAccessibleByCategory`에서는 `User`라는 명칭을 사용하셨는데, 다른 목적 때문에 다르게 이름을 명명하신 것인지 궁금해요!

2024-08-25 05:35 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +    }*/
수정 전 코드를 비교하면서 작업하다가 삭제를 안 하고 올렸네요! 제거하였습니다

2024-08-25 05:53 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +    private boolean isMemberAccessible(String url, Authentication authentication) {
먼저 파일에 접근할 수 있는 사용자는 **로그인하지 않은 사용자와 로그인한 사용자**로 나눌 수 있습니다. 그리고 **로그인한 사용자는 GUEST, USER, ADMIN, SUPER로 구분**됩니다.

파일 접근을 시도할 때 거치는 로직에 따라서 User -> Member로 단어가 변하는데, 이 과정을 설명드릴게요.

1.  먼저 `FileAccessControlFilter`를 거칩니다.
이때 `isUserAccessibleAtFile`이라는 메소드를 호출합니다. 이때는 로그인하지 않은 사용자가 접근을 시도할 수 있어요. 따라서 우리 프로젝트 내에서 사용자를 칭하는 Member라는 단어가 아닌 User라는 단어를 사용했습니다.

2. 그리고 `isUserAccessibleAtFile` 메소드안에서 `isUserAccessibleByCategory` 메소드를 호출합니다. 해당 부분에서는 여전히 로그인하지 않은 사용자가 처리되지 않았기 때문에 `isUserAccessibleByCategory`라고 User 단어를 사용했습니다. 

3. `isUserAccessibleByCategory` 내부에서 아래의 로직을 거치고 나서야 로그인한 사용자 즉 Member의 카테고리별 접근 권한을 따질 수 있어요. 

``` 
if (AuthUtil.isUserUnAuthenticated(authentication)) {
            return false;
        }
```

따라서 위의 코드 이후에 나타나는 
```
return categoryAccessMap.getOrDefault(category, (u, a) -> false).apply(url, authentication);
```
에서 `members`와 `assignments `카테고리에 대해서는 로그인한 사용자 중 ROLE 레벨에 따라 접근 검사를 하기 때문에 이제는 `isMemberAccessible, isAssignmentAccessible`처럼 Member라는 단어를 사용했어요.
```
private final Map<String, BiFunction<String, Authentication, Boolean>> categoryAccessMap = Map.of(
            "boards", (url, auth) -> true,
            "profiles", (url, auth) -> true,
            "membership-fees", (url, auth) -> true,
            "activity-photos", (url, auth) -> true,
            "members", this::isMemberAccessible,
            "assignments", this::isAssignmentAccessible
    );
```

2024-08-25 06:22 UTC, limehee approved these changes
새로 추가될 주차별 활동 파일 업로드 API에 대한 카테고리를 추가해주셨군요. 반영 감사합니다 :)

2024-08-25 06:25 UTC, mingmingmon commented
> 새로 추가될 주차별 활동 파일 업로드 API에 대한 카테고리를 추가해주셨군요. 반영 감사합니다 :)
주차별 활동 파일에 대한 접근 권한을 USER 이상, 그리고 활동에 참여하는 member만 하기 위해서 추가 작업중입니다! 수정 커밋 올리고 다시 리뷰 요청 드릴게요

2024-08-25 06:26 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +    private boolean isMemberAccessible(String url, Authentication authentication) {
**로그인 한 Member**와 **그렇지 않은 User**의 차이가 있는 것이었군요.
정성스러운 답변 정말 감사합니다!!

2024-08-25 06:27 UTC, SongJaeHoonn approved these changes

2024-08-25 06:45 UTC, SongJaeHoonn commented
> 주차별 활동 파일에 대한 접근 권한을 USER 이상, 그리고 활동에 참여하는 member만 하기 위해서 추가 작업중입니다! 수정 커밋 올리고 다시 리뷰 요청 드릴게요

즉각적이고 빠른 수정해주셔서 감사합니다. 고생하셨습니다!

2024-08-25 06:45 UTC, SongJaeHoonn approved these changes

2024-08-25 06:50 UTC, limehee commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        Long activityGroupId = Long.parseLong(parts[4]);
```java
fileService.buildPath("assignments", activityGroupId, activityGroupBoardId);
```
위 코드에 따라 url은 `assignments/{activityGroupId}{activityGroupBoardId}`로 생성됩니다.
따라서, `/`로 문자열을 분리했을 때,  `activityGroupId`는 `parts[1]`로 예상되는데, 확인 부탁드려도 될까요?

2024-08-25 07:04 UTC, mingmingmon commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        Long activityGroupId = Long.parseLong(parts[4]);
해당 부분 로그를 확인해보니, 저희 파일 경로 생성 정책에 따라 경로가 생성되면,
parts[4] 부분을 파싱해야 activityGroupId를 얻을 수 있습니다. 

보안상 실제 파일 생성 경로를 다 올려드릴 수는 없어서 @limehee 님과 직접 테스트 결과 및 로그를 확인하였습니다!

2024-08-25 07:32 UTC, limehee commented on src/main/java/page/clab/api/global/common/file/application/FileService.java
> +        Long activityGroupId = Long.parseLong(parts[4]);
네 감사합니다!

2024-08-25 07:32 UTC, limehee approved these changes

2024-08-25 07:32 UTC, merged