ActivityGroupBoard 관련 수정 완료
KGU-C-Lab/clab-platforms-server pull request #506
Opened 2024-08-24 15:52 UTC by SongJaeHoonn

## Summary

> #500 

1. 과제 제출을 한 사람이 여러 번 할 수 있는 문제로 인해, 과제 제출을 1회만 가능하도록 validation을 추가했습니다.
2. 게시물의 카테고리별 권한 제어 로직을 작성했습니다.
- 게시물 생성
  - 카테고리가 `NOTICE`, `WEEKLY_ACTIVITY`,  `ASSIGNMENT`, `FEEDBACK`인 경우에, 권한이 ADMIN 이상이거나, 그룹의 리더만 게시물을 작성할 수 있도록 작성했습니다.

- 게시물 조회
  - 카테고리가 SUBMIT이거나 FEEDBACK일 시, 과제 제출자 혹은 그룹의 리더만이 해당 게시물에 접근 가능하도록 작성했습니다.

## Tasks

- 과제 제출을 1회만 가능하도록 validation 추가
- 과제 수정 시 updatedAt 정보가 수정되는지 확인
- 게시글 카테고리별 생성 권한 제어
- 게시글 카테고리별 조회 권한 제어

## ETC

![스크린샷 2024-08-24 032145](https://github.com/user-attachments/assets/90afaa68-36d1-46a2-a9f7-9e67c2f7a06b)
과제 수정 시, updatedAt 정보가 정상적으로 수정됨을 확인했습니다.

## Screenshot

### 과제 제출 1회만 가능하도록 validation 추가
```
{
  "success": true,
  "data": {
    "currentPage": 0,
    "hasPrevious": false,
    "hasNext": false,
    "totalPages": 1,
    "totalItems": 3,
    "take": 3,
    "items": [
      {
        "id": 4,
        "memberId": "202014941",
        "memberName": "송재훈",
        "parentId": 3,
        "category": "SUBMIT",
        "title": "202014941 1주차 과제 제출",
        "content": "1주차 과제 제출하도록 하겠습니다.",
        "files": [],
        "dueDateTime": "2024-08-29T17:17:56.951",
        "createdAt": "2024-08-24T03:02:06.071873",
        "updatedAt": "2024-08-24T03:02:06.071873"
      },
      {
        "id": 3,
        "memberId": "superuser",
        "memberName": "관리자",
        "parentId": 2,
        "category": "ASSIGNMENT",
        "title": "1주차 과제",
        "content": "1주차 과제입니다. 제출해주세요.",
        "files": [],
        "dueDateTime": "2024-08-29T17:17:56.951",
        "createdAt": "2024-08-24T02:58:37.567156",
        "updatedAt": "2024-08-24T02:58:37.567156"
      },
      {
        "id": 2,
        "memberId": "superuser",
        "memberName": "관리자",
        "parentId": null,
        "category": "WEEKLY_ACTIVITY",
        "title": "1주차 활동",
        "content": "1주차입니다.",
        "files": [],
        "dueDateTime": "2024-08-30T17:17:56.951",
        "createdAt": "2024-08-24T02:56:42.017053",
        "updatedAt": "2024-08-24T02:56:42.017053"
      }
    ]
  }
}
```
위 상태에서, 해당 주차에서 한번 더 과제 제출 진행
- 결과
![스크린샷 2024-08-24 031838](https://github.com/user-attachments/assets/3461fa6d-e44b-433f-87b3-5d2fb92da113)

### 게시글 카테고리별 생성 권한 제어
- Accepted되지 않은 멤버가 게시물을 생성하려고 한 결과
![스크린샷 2024-08-24 035155](https://github.com/user-attachments/assets/1b71fd6f-b263-4d09-9b06-b361a9a7f386)

### 게시글 카테고리별 조회 권한 제어
- 활동 멤버가 아닌 인원이 활동 그룹 게시판 단일 조회
![스크린샷 2024-08-24 213001](https://github.com/user-attachments/assets/ed58cada-aeb9-46ab-a389-d83fbf17fba2)
활동 그룹 게시판 조회, 나의 제출 과제 및 피드백 조회를 제외하고는 전부 같은 403 Error가 발생합니다.

![스크린샷 2024-08-24 222322](https://github.com/user-attachments/assets/953cfd57-aa32-4f76-b3a5-a56378df8fb7)
위와 같이 제출된 과제가 두 개 있는 상태이고, 201912000이 로그인한 상태에서,
- 활동 그룹 id에 대한 카테고리별 게시판 조회
![스크린샷 2024-08-24 222442](https://github.com/user-attachments/assets/1b09c0c6-1e23-4054-bc8b-75d78c37b57f)

- 활동 그룹 게시판 계층 구조적 조회
![스크린샷 2024-08-24 232938](https://github.com/user-attachments/assets/125cebc5-a5b7-42f5-a43c-bf2ac6608480)

- 활동 그룹 게시판 단일 조회
  - 본인의 과제가 아닌 다른 사람의 과제를 조회했을 때
![스크린샷 2024-08-24 231825](https://github.com/user-attachments/assets/71bd5d6d-9480-4906-9fbf-4845aa795429)
  - 본인 과제를 조회했을 때
![스크린샷 2024-08-24 231924](https://github.com/user-attachments/assets/2c0d4e30-0fc6-42f4-a342-01a5665fa4cb)

- 나의 제출 과제 및 피드백 조회(201912000으로 로그인)
![스크린샷 2024-08-24 232938](https://github.com/user-attachments/assets/a80adf17-9b23-4c84-bc01-7f9ede30c79a)

*이 외에, Leader로 로그인 후 모든 api를 조회해봤을 때, 일부가 아닌 모든 데이터가 정상적으로 나오는 것을 확인했습니다.*

2024-08-24 16:18 UTC, limehee requested changes

2024-08-24 16:18 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        validateAlreadySubmittedAssignmentThisWeek(requestDto.getCategory(), parentId, currentMember.getId());
validation에 대한 메소드 3개가 나열되어있는거라서 validate 메소드끼리는 개행 안해도 될 것 같아요.

2024-08-24 16:18 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        //NOTICE, WEEKLY_ACTIVITY, ASSIGNMENT, FEEDBACK 카테고리에서 권한이 ADMIN 이상이 아니거나, 리더가 아니면 예외처리
주석 `//` 뒤에 공백 1개 추가 부탁드려요.

2024-08-24 16:18 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        boolean isRequireAdminOrLeaderCategory = category == ActivityGroupBoardCategory.NOTICE ||
`ActivityGroupBoardCategory` Enum 클래스 안에 `isNotice()`, `inWeeklyActivity()`같은 메소드를 정의해서 사용하면 가독성에 더 좋을 것 같아요.

2024-08-24 16:18 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +                    && parentBoard.getMemberId().equals(currentMember.getId());
`ActivityGroupBoard`에 `isOwner()` 메소드를 이용하면 가독성을 높이고, DDD에 부합한 코드를 작성할 수 있어요.

2024-08-24 16:18 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +            if(hasSubmitted) {
if와 `(` 사이에 공백 추가 부탁드려요.

2024-08-24 16:18 UTC, limehee commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        if(!activityGroupMemberService.isGroupMember(board.getActivityGroup(), currentMember.getId())) {
Controller에서 호출하는 Service 메소드는 구체적인 구현보다는 프로세스의 흐름을 보이려고 하고있어요. 유효성 검사 로직은 별도의 메소드로 분리해도 좋을 것 같아요. 흐름 외에도 해당 유효성 검사는 다른 부분에서도 사용되고 있어서 메소드 분리하는게 중복 코드 제거에도 도움이 될 것으로 보여요.

2024-08-24 16:44 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        boolean isRequireAdminOrLeaderCategory = category == ActivityGroupBoardCategory.NOTICE ||
기능에 집중하다보니, 가독성이 많이 떨어지네요. 피드백 감사합니다! enum 클래스 안에 boolean 메서드를 추가하는 방식으로 진행하겠습니다.

2024-08-24 16:59 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +                    && parentBoard.getMemberId().equals(currentMember.getId());
피드백 감사합니다. 사소한 변경에서 좋은 코드가 나오는군요. 변경 완료했습니다!!

2024-08-24 17:21 UTC, SongJaeHoonn commented on src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
> +        if(!activityGroupMemberService.isGroupMember(board.getActivityGroup(), currentMember.getId())) {
말씀을 듣고 변경해보고 나니 정말 깔끔해지네요. 해당 로직을 사용하는 부분이 많아 더욱 효과적이었던 것 같습니다. 피드백 감사합니다!

2024-08-25 00:11 UTC, limehee approved these changes

2024-08-25 04:44 UTC, mingmingmon approved these changes
리팩토링 작업 한 차례 끝내고 나니 더 깔끔해진 것 같네요! 고생하셨습니다.

2024-08-25 04:47 UTC, merged